const birds = [
  {id:'passer-domesticus',scientific:'Passer domesticus',en:'House sparrow',sv:'Gråsparv',zh:'家麻雀',pinyin:'jiā má què',image:'images/sparrow.jpg',credit:'Charles J. Sharp · CC BY-SA 3.0',source:'https://commons.wikimedia.org/wiki/File:House_sparrow_(Passer_domesticus).jpg'},
  {id:'anas-platyrhynchos',scientific:'Anas platyrhynchos',en:'Mallard',sv:'Gräsand',zh:'绿头鸭',pinyin:'lǜ tóu yā',image:'images/mallard.jpg',credit:'Imran Shah · CC BY-SA 2.0',source:'https://commons.wikimedia.org/wiki/File:Mallard_(Anas_platyrhynchos)_(26436726209).jpg'},
  {id:'pica-pica',scientific:'Pica pica',en:'Eurasian magpie',sv:'Skata',zh:'欧亚喜鹊',pinyin:'ōu yà xǐ què',image:'images/magpie.jpg',credit:'Alexis Lours · CC BY 4.0',source:'https://commons.wikimedia.org/wiki/File:Eurasian_magpie_(Pica_pica).jpg'},
  {id:'parus-major',scientific:'Parus major',en:'Great tit',sv:'Talgoxe',zh:'欧亚大山雀',pinyin:'ōu yà dà shān què',image:'images/great-tit.jpg',credit:'caroline legg · CC BY 2.0',source:'https://commons.wikimedia.org/wiki/File:Great_tit_-_Parus_major_(51988627968).jpg'},
  {id:'cyanistes-caeruleus',scientific:'Cyanistes caeruleus',en:'Eurasian blue tit',sv:'Blåmes',zh:'蓝山雀',pinyin:'lán shān què',image:'images/blue-tit.jpg',credit:'TRinaud · CC BY 4.0',source:'https://commons.wikimedia.org/wiki/File:Eurasian_blue_tit_(Cyanistes_caeruleus)_2021.jpg'},
  {id:'turdus-merula',scientific:'Turdus merula',en:'Common Blackbird',sv:'koltrast',zh:'欧亚乌鸫',pinyin:'ōu yà wū dōng',image:'images/turdus-merula.jpg',credit:'Kahvilokki · CC BY-SA 4.0',source:'https://commons.wikimedia.org/wiki/File:20190722_Turdus_Merula_02.jpg'},
  {id:'erithacus-rubecula',scientific:'Erithacus rubecula',en:'European robin',sv:'rödhake',zh:'欧亚鸲',pinyin:'ōu yà qú',image:'images/erithacus-rubecula.jpg',credit:'Francis C. Franklin · CC BY-SA 3.0',source:'https://commons.wikimedia.org/wiki/File:Erithacus_rubecula_with_cocked_head.jpg'},
  {id:'fringilla-coelebs',scientific:'Fringilla coelebs',en:'Eurasian Chaffinch',sv:'bofink',zh:'苍头燕雀',pinyin:'cāng tóu yàn què',image:'images/fringilla-coelebs.jpg',credit:'Gilles San Martin from Namur, Belgium · CC BY-SA 2.0',source:'https://commons.wikimedia.org/wiki/File:Fringilla_coelebs_(5577610542).jpg'},
  {id:'chloris-chloris',scientific:'Chloris chloris',en:'European Greenfinch',sv:'grönfink',zh:'欧金翅雀',pinyin:'ōu jīn chì què',image:'images/chloris-chloris.jpg',credit:'Estormiz · CC0',source:'https://commons.wikimedia.org/wiki/File:Carduelis_chloris_Oulu_20120507.JPG'},
  {id:'pyrrhula-pyrrhula',scientific:'Pyrrhula pyrrhula',en:'Eurasian Bullfinch',sv:'domherre',zh:'红腹灰雀',pinyin:'hóng fù huī què',image:'images/pyrrhula-pyrrhula.jpg',credit:'Francis Franklin · CC BY-SA 3.0',source:'https://commons.wikimedia.org/wiki/File:Bullfinch_male.jpg'},
  {id:'carduelis-carduelis',scientific:'Carduelis carduelis',en:'European Goldfinch',sv:'steglits',zh:'红额金翅雀',pinyin:'hóng é jīn chì què',image:'images/carduelis-carduelis.jpg',credit:'Pierre Dalous · CC BY-SA 3.0',source:'https://commons.wikimedia.org/wiki/File:Carduelis_carduelis_(2012).jpg'},
  {id:'sturnus-vulgaris',scientific:'Sturnus vulgaris',en:'Common Starling',sv:'stare',zh:'紫翅椋鸟',pinyin:'zǐ chì liáng niǎo',image:'images/sturnus-vulgaris.jpg',credit:'marsupium photography · CC BY-SA 2.0',source:'https://commons.wikimedia.org/wiki/File:Common_Starling,_Blyth_(12598795653).jpg'},
  {id:'coloeus-monedula',scientific:'Coloeus monedula',en:'Western Jackdaw',sv:'kaja',zh:'寒鸦',pinyin:'hán yā',image:'images/coloeus-monedula.jpg',credit:'Darkone · CC BY-SA 2.5',source:'https://commons.wikimedia.org/wiki/File:Dohle_(Corvus_monedula)_d1.jpg'},
  {id:'corvus-cornix',scientific:'Corvus cornix',en:'Hooded Crow',sv:'gråkråka',zh:'冠小嘴乌鸦',pinyin:'guān xiǎo zuǐ wū yā',image:'images/corvus-cornix.jpg',credit:'Donald Hobern from Copenhagen, Denmark · CC BY 2.0',source:'https://commons.wikimedia.org/wiki/File:Corvus_cornix_(33515567265).jpg'},
  {id:'corvus-corax',scientific:'Corvus corax',en:'Northern Raven',sv:'korp',zh:'渡鸦',pinyin:'dù yā',image:'images/corvus-corax.jpg',credit:'Accipiter (R. Altenkamp, Berlin) · CC BY-SA 3.0',source:'https://commons.wikimedia.org/wiki/File:Corvus_corax_ad_berlin_090516.jpg'},
  {id:'corvus-frugilegus',scientific:'Corvus frugilegus',en:'Rook',sv:'råka',zh:'秃鼻乌鸦',pinyin:'tū bí wū yā',image:'images/corvus-frugilegus.jpg',credit:'Brian Snelson from Hockley, Essex, England · CC BY 2.0',source:'https://commons.wikimedia.org/wiki/File:Corvus_frugilegus_-Dartmoor,_Devon,_England-8.jpg'},
  {id:'columba-palumbus',scientific:'Columba palumbus',en:'Common Wood Pigeon',sv:'ringduva',zh:'斑尾林鸽',pinyin:'bān wěi lín gē',image:'images/columba-palumbus.jpg',credit:'Don Loarie · CC BY 4.0',source:'https://commons.wikimedia.org/wiki/File:Columba_palumbus_ssp._palumbus.jpg'},
  {id:'columba-livia',scientific:'Columba livia',en:'Rock Dove',sv:'klippduva',zh:'原鸽',pinyin:'yuán gē',image:'images/columba-livia.jpg',credit:'william_stephens · CC BY 4.0',source:'https://commons.wikimedia.org/wiki/File:Columba_livia_(Rock_Dove,_wild),_Duncansby_Head,_Caithness,_Scotland_1.jpg'},
  {id:'dendrocopos-major',scientific:'Dendrocopos major',en:'Great Spotted Woodpecker',sv:'Större hackspett',zh:'大斑啄木鸟',pinyin:'dà bān zhuó mù niǎo',image:'images/dendrocopos-major.jpg',credit:'Bengt Nyman from Vaxholm, Sweden · CC BY 2.0',source:'https://commons.wikimedia.org/wiki/File:Dendrocopos_major_EM1B2679_(35219263071).jpg'},
  {id:'sitta-europaea',scientific:'Sitta europaea',en:'Eurasian Nuthatch',sv:'nötväcka',zh:'普通䴓',pinyin:'pǔ tōng shī',image:'images/sitta-europaea.jpg',credit:'Stefan Berndtsson · CC BY 2.0',source:'https://commons.wikimedia.org/wiki/File:Sitta_europaea_europaea,_Slottsskogen,_G%C3%B6teborg,_Sweden_3.jpg'},
  {id:'apus-apus',scientific:'Apus apus',en:'Common Swift',sv:'tornseglare',zh:'普通楼燕',pinyin:'pǔ tōng lóu yàn',image:'images/apus-apus.jpg',credit:'Alexis Lours · CC BY 4.0',source:'https://commons.wikimedia.org/wiki/File:Common_Swift_2025_07_18_02_(cropped).jpg'},
  {id:'hirundo-rustica',scientific:'Hirundo rustica',en:'Barn Swallow',sv:'Ladusvala',zh:'家燕',pinyin:'jiā yàn',image:'images/hirundo-rustica.jpg',credit:'Morhaf Aljanee · CC BY-SA 3.0',source:'https://commons.wikimedia.org/wiki/File:Barn_Swallow_(95504589).jpeg'},
  {id:'motacilla-alba',scientific:'Motacilla alba',en:'White wagtail',sv:'sädesärla',zh:'白鹡鸰',pinyin:'bái jí líng',image:'images/motacilla-alba.jpg',credit:'Jac. Janssen from BAARLO LB, NL · CC BY 2.0',source:'https://commons.wikimedia.org/wiki/File:20180415_015_Winterswijk_Witte_kwikstaart_(40785272624).jpg'},
  {id:'turdus-pilaris',scientific:'Turdus pilaris',en:'Fieldfare',sv:'björktrast',zh:'田鸫',pinyin:'tián dōng',image:'images/turdus-pilaris.jpg',credit:'Frankie Fouganthin · CC BY-SA 4.0',source:'https://commons.wikimedia.org/wiki/File:Bj%C3%B6rktrast_(Turdus_pilaris)-4.jpg'},
  {id:'turdus-philomelos',scientific:'Turdus philomelos',en:'Song Thrush',sv:'taltrast',zh:'欧歌鸫',pinyin:'ōu gē dōng',image:'images/turdus-philomelos.jpg',credit:'Charles J. Sharp · CC BY-SA 4.0',source:'https://commons.wikimedia.org/wiki/File:Song_thrush_(Turdus_philomelos_philomelos).jpg'}
];
const trees = [
  {id:'quercus-robur',scientific:'Quercus robur',en:'Pedunculate oak',sv:'ek',zh:'夏栎',pinyin:'xià lì',image:'images/trees/quercus-robur.jpg',credit:'Algirdas at Lithuanian Wikipedia · Public domain',source:'https://commons.wikimedia.org/wiki/File:Paprastasis_azuolas.JPG'},
  {id:'pinus-sylvestris',scientific:'Pinus sylvestris',en:'Scots pine',sv:'tall',zh:'欧洲赤松',pinyin:'ōu zhōu chì sōng',image:'images/trees/pinus-sylvestris.jpg',credit:'Hello, I am Bruce on Flickr · CC BY-SA 2.0',source:'https://commons.wikimedia.org/wiki/File:Pinus_sylvestris_Glenmuick.jpg'},
  {id:'betula-pendula',scientific:'Betula pendula',en:'Silver birch',sv:'vårtbjörk',zh:'垂枝桦',pinyin:'chuí zhī huà',image:'images/trees/betula-pendula.jpg',credit:'Percita at Flickr · CC BY-SA 2.0',source:'https://commons.wikimedia.org/wiki/File:Betula_pendula_Finland.jpg'},
  {id:'picea-abies',scientific:'Picea abies',en:'Norway spruce',sv:'gran',zh:'欧洲云杉',pinyin:'ōu zhōu yún shān',image:'images/trees/picea-abies.jpg',credit:'Ivar Leidus · CC BY-SA 3.0 ee',source:'https://commons.wikimedia.org/wiki/File:Kuusk_Keila-Paldiski_rdt_%C3%A4%C3%A4res.jpg'},
  {id:'acer-platanoides',scientific:'Acer platanoides',en:'Norway maple',sv:'lönn',zh:'挪威枫',pinyin:'nuó wēi fēng',image:'images/trees/acer-platanoides.jpg',credit:'Martin Bobka (= Martin120 ) · CC BY-SA 2.5',source:'https://commons.wikimedia.org/wiki/File:Spitz-Ahorn(mbo).jpg'},
  {id:'sorbus-aucuparia',scientific:'Sorbus aucuparia',en:'Rowan',sv:'rönn',zh:'欧洲花楸',pinyin:'ōu zhōu huā qiū',image:'images/trees/sorbus-aucuparia.jpg',credit:'Eeno11 · CC BY-SA 3.0',source:'https://commons.wikimedia.org/wiki/File:Rowan_tree_20081002b.jpg'},
  {id:'populus-tremula',scientific:'Populus tremula',en:'European aspen',sv:'asp',zh:'欧洲山杨',pinyin:'ōu zhōu shān yáng',image:'images/trees/populus-tremula.jpg',credit:'Øyvind Holmstad · CC BY-SA 4.0',source:'https://commons.wikimedia.org/wiki/File:Ospeholt_i_Hurdal.JPG'},
  {id:'alnus-glutinosa',scientific:'Alnus glutinosa',en:'Black alder',sv:'klibbal',zh:'欧洲桤木',pinyin:'ōu zhōu qī mù',image:'images/trees/alnus-glutinosa.jpg',credit:'Willow · CC BY 2.5',source:'https://commons.wikimedia.org/wiki/File:Alnus_glutinosa_011.jpg'},
  {id:'tilia-cordata',scientific:'Tilia cordata',en:'Small-leaved lime',sv:'skogslind',zh:'小叶椴',pinyin:'xiǎo yè duàn',image:'images/trees/tilia-cordata.jpg',credit:'ImreKiss · CC BY 3.0',source:'https://commons.wikimedia.org/wiki/File:Tilia_cordata,_Lipa2009.jpg'},
  {id:'fagus-sylvatica',scientific:'Fagus sylvatica',en:'European beech',sv:'bok',zh:'欧洲山毛榉',pinyin:'ōu zhōu shān máo jǔ',image:'images/trees/fagus-sylvatica.jpg',credit:'Malene Thyssen · CC BY-SA 3.0',source:'https://commons.wikimedia.org/wiki/File:Grib_skov.jpg'}
];
const flowers = [
  {id:'taraxacum',scientific:'Taraxacum',en:'Dandelion',sv:'maskros',zh:'蒲公英',pinyin:'pú gōng yīng',image:'images/flowers/taraxacum.jpg',credit:'Greg Hume · CC BY-SA 3.0',source:'https://commons.wikimedia.org/wiki/File:DandelionFlower.jpg'},
  {id:'bellis-perennis',scientific:'Bellis perennis',en:'Common daisy',sv:'tusensköna',zh:'雏菊',pinyin:'chú jú',image:'images/flowers/bellis-perennis.jpg',credit:'m.dolores paderne sa… · CC BY-SA 3.0',source:'https://commons.wikimedia.org/wiki/File:Belis_peremnis_-_panoramio.jpg'},
  {id:'leucanthemum-vulgare',scientific:'Leucanthemum vulgare',en:'Oxeye daisy',sv:'prästkrage',zh:'法兰西菊',pinyin:'fǎ lán xī jú',image:'images/flowers/leucanthemum-vulgare.jpg',credit:'Victor M. Vicente Selvas · Public domain',source:'https://commons.wikimedia.org/wiki/File:Leucanthemum_vulgare15.06.07.JPG'},
  {id:'trifolium-pratense',scientific:'Trifolium pratense',en:'Red clover',sv:'rödklöver',zh:'红菽草',pinyin:'hóng shū cǎo',image:'images/flowers/trifolium-pratense.jpg',credit:'Ivar Leidus · CC BY-SA 4.0',source:'https://commons.wikimedia.org/wiki/File:Trifolium_pratense_-_Keila2.jpg'},
  {id:'ranunculus-acris',scientific:'Ranunculus acris',en:'Meadow buttercup',sv:'smörblomma',zh:'高毛茛',pinyin:'gāo máo gèn',image:'images/flowers/ranunculus-acris.jpg',credit:'Alinja · CC BY-SA 4.0',source:'https://commons.wikimedia.org/wiki/File:Ranunculus_acris_niittyleinikki.jpg'},
  {id:'tussilago-farfara',scientific:'Tussilago farfara',en:'Coltsfoot',sv:'hästhov',zh:'款冬',pinyin:'kuǎn dōng',image:'images/flowers/tussilago-farfara.jpg',credit:'Andreas Trepte · CC BY-SA 2.5',source:'https://commons.wikimedia.org/wiki/File:Coltsfoot.jpg'},
  {id:'anemone-nemorosa',scientific:'Anemone nemorosa',en:'Wood anemone',sv:'vitsippa',zh:'栎林银莲花',pinyin:'lì lín yín lián huā',image:'images/flowers/anemone-nemorosa.jpg',credit:'Lilly M · CC BY-SA 3.0',source:'https://commons.wikimedia.org/wiki/File:Anemone_nemorosa_001.JPG'},
  {id:'hepatica-nobilis',scientific:'Hepatica nobilis',en:'Common hepatica',sv:'blåsippa',zh:'三角草',pinyin:'sān jiǎo cǎo',image:'images/flowers/hepatica-nobilis.jpg',credit:'Archenzo · CC BY-SA 3.0',source:'https://commons.wikimedia.org/wiki/File:Hepatica_nobilis_plant.JPG'},
  {id:'convallaria-majalis',scientific:'Convallaria majalis',en:'Lily of the valley',sv:'liljekonvalj',zh:'铃兰',pinyin:'líng lán',image:'images/flowers/convallaria-majalis.jpg',credit:'Ivar Leidus · CC BY-SA 4.0',source:'https://commons.wikimedia.org/wiki/File:Convallaria_majalis_inflorescence_-_Keila.jpg'},
  {id:'campanula-rotundifolia',scientific:'Campanula rotundifolia',en:'Harebell',sv:'liten blåklocka',zh:'圆叶风铃草',pinyin:'yuán yè fēng líng cǎo',image:'images/flowers/campanula-rotundifolia.jpg',credit:'Tigerente · CC BY-SA 3.0',source:'https://commons.wikimedia.org/wiki/File:Campanula_rotondifolia.jpg'}
];
const spanish = [
  {id:'chico',es:'Chico',sv:'kille',image:'images/spanish/chico.png'},
  {id:'chica',es:'Chica',sv:'tjej',image:'images/spanish/chica.png'},
  {id:'yo-tambien',es:'Yo también',sv:'jag också',image:'images/spanish/conversacion.png'},
  {id:'la-capital',es:'La capital',sv:'huvudstaden',image:'images/spanish/ciudad.png'},
  {id:'una-ciudad',es:'Una ciudad',sv:'en stad',image:'images/spanish/ciudad.png'},
  {id:'que',es:'Que',sv:'som',image:'images/spanish/conversacion.png'},
  {id:'se-llama',es:'Se llama',sv:'(den) heter',image:'images/spanish/conversacion.png'},
  {id:'en',es:'En',sv:'i',image:'images/spanish/ciudad.png'},
  {id:'si',es:'Sí',sv:'ja',image:'images/spanish/conversacion.png'},
  {id:'no',es:'No',sv:'nej',image:'images/spanish/conversacion.png'},
  {id:'pero',es:'Pero',sv:'men',image:'images/spanish/conversacion.png'}
];
const topics = {
  birds:{title:'Birds',singular:'bird',subtitle:'25 birds found in Sweden · English, Swedish, Mandarin',image:'images/blue-tit.jpg',items:birds,languages:[['en','English'],['sv','Swedish'],['zh','Mandarin']]},
  trees:{title:'Trees',singular:'tree',subtitle:'10 common trees in Sweden · English, Swedish, Mandarin',image:'images/trees/quercus-robur.jpg',items:trees,languages:[['en','English'],['sv','Swedish'],['zh','Mandarin']]},
  flowers:{title:'Flowers',singular:'flower',subtitle:'10 common flowers in Sweden · English, Swedish, Mandarin',image:'images/flowers/bellis-perennis.jpg',items:flowers,languages:[['en','English'],['sv','Swedish'],['zh','Mandarin']]},
  spanish:{title:'Kapitelord 1–4',subtitle:'Spanish homework · 1 October',image:'images/spanish/ciudad.png',items:spanish,languages:[['es','Spanish'],['sv','Swedish']]}
};
const KEY='fact-learner-v1';
const freshPractice=id=>({index:0,mode:id==='spanish'?'sv':'picture',revealed:false,results:{}});
const freshMatch=id=>({players:['Player 1','Player 2'],scores:[0,0],turn:0,itemId:topics[id].items[0].id,awards:{},history:[],ended:false});
let stored={};try{stored=JSON.parse(localStorage.getItem(KEY)||'{}')||{}}catch{}
const state={
  page:'home',topicId:'birds',
  practices:Object.fromEntries(Object.keys(topics).map(id=>[id,{...freshPractice(id),...(stored.practices?.[id]||(id==='birds'?stored.practice:null))}])),
  matches:Object.fromEntries(Object.keys(topics).map(id=>[id,{...freshMatch(id),...(stored.matches?.[id]||(id==='birds'?stored.match:null))}]))
};
if(stored.match?.birdId&&!stored.match.itemId)state.matches.birds.itemId=stored.match.birdId;
state.matches.birds.history=state.matches.birds.history.map(s=>({...s,itemId:s.itemId||s.birdId||birds[0].id}));
const app=document.querySelector('#app');
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const topic=()=>topics[state.topicId];
const practiceState=()=>state.practices[state.topicId];
const shuffle=items=>{const result=[...items];for(let i=result.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[result[i],result[j]]=[result[j],result[i]]}return result};
function practiceQueue(){const p=practiceState(),ids=topic().items.map(item=>item.id);if(!Array.isArray(p.queue)){p.queue=shuffle(ids);p.catalog=ids;save()}else{const known=p.catalog|| (state.topicId==='birds'?birds.slice(0,5).map(x=>x.id):ids);p.queue=p.queue.filter(id=>ids.includes(id));const added=ids.filter(id=>!known.includes(id));if(added.length)p.queue.push(...shuffle(added));p.catalog=ids;if(added.length)save()}return p.queue}
const matchState=()=>state.matches[state.topicId];
const itemImage=(item,hidden=false)=>`<img class="hero-img" src="${item.image}" alt="${hidden?'Illustration or photo; answer hidden until reveal':esc(item.en||item.es)}">`;
const itemNames=item=>item.zh?`<dl class="names"><dt>English</dt><dd>${esc(item.en)}</dd><dt>Swedish</dt><dd>${esc(item.sv)}</dd><dt>Mandarin</dt><dd>${esc(item.zh)} (${esc(item.pinyin)})</dd></dl>`:`<dl class="names"><dt>Spanish</dt><dd>${esc(item.es)}</dd><dt>Swedish</dt><dd>${esc(item.sv)}</dd></dl>`;
const credit=item=>item.source?`<p class="credit">Photo: <a href="${item.source}" target="_blank" rel="noopener">${esc(item.credit)}</a></p>`:'';
const back=()=>`<button class="back" data-page="home">← All topics</button>`;
const nav=()=>`<div class="topic-nav"><button class="btn secondary" data-page="topic">Overview</button><button class="btn secondary" data-page="learn">Learn</button><button class="btn secondary" data-page="practice">Practice</button><button class="btn secondary" data-page="match">Match</button></div>`;

function home(){return `<h1>Topics</h1><div class="topic-grid">${Object.entries(topics).map(([id,t])=>`<button class="topic" data-topic="${id}" aria-label="Open ${esc(t.title)}"><img src="${t.image}" loading="lazy" decoding="async" alt=""><span class="topic-body"><span class="eyebrow">${t.items.length} facts</span><span class="topic-title">${esc(t.title)}</span><span class="topic-subtitle">${esc(t.subtitle)}</span><span class="topic-open">Open topic →</span></span></button>`).join('')}</div>`}
function overview(){const t=topic(),p=practiceState(),done=Object.values(p.results).filter(x=>x==='got').length;return `${back()}<p class="eyebrow">Your topic</p><h1>${esc(t.title)}</h1><p class="lead">${esc(t.subtitle)}</p><div class="panel"><p class="progress">${done} of ${t.items.length} marked Got it</p><h2>What would you like to do?</h2><div class="row"><button class="btn" data-page="learn">Learn</button><button class="btn secondary" data-page="practice">Practice</button><button class="btn secondary" data-page="match">Match</button></div></div><p class="small muted">Progress and match scores stay in this browser.</p>`}
function learn(){const t=topic();return `${back()}${nav()}<p class="eyebrow">${esc(t.title)} · Learn</p><h1>Get to know it.</h1><p class="lead">Read each fact and its matching words.</p><div class="grid">${t.items.map(item=>`<article class="bird"><img src="${item.image}" loading="lazy" decoding="async" alt="${esc(item.en||item.es)}"><h3>${esc(item.en||item.es)}</h3>${item.scientific?`<p class="meta"><i>${esc(item.scientific)}</i></p>`:''}${itemNames(item)}${credit(item)}</article>`).join('')}</div><p class="small"><a href="credits.html">Image and word sources</a></p>`}
function practice(){const t=topic(),p=practiceState(),queue=practiceQueue(),item=t.items.find(x=>x.id===queue[0]),done=t.items.length-queue.length;const options=t.singular?[['picture','Picture only'],...t.languages]:t.languages;if(!item)return `<div class="practice-shell"><div class="practice-head"><button class="back" data-page="topic">← ${esc(t.title)}</button></div><p class="eyebrow">Practice · ${esc(t.title)}</p><h1>Session complete.</h1><p class="lead">You marked all ${t.items.length} items Got it.</p><div class="practice-actions"><button class="btn" id="restart">Practice again</button></div></div>`;const prompt=p.mode==='picture'?`What ${esc(t.singular)} is this?`:esc(item[p.mode]);return `<div class="practice-shell"><div class="practice-head"><button class="back" data-page="topic">← ${esc(t.title)}</button><span class="practice-count">${queue.length} left</span></div><p class="eyebrow">Practice · ${esc(t.title)}</p><div class="row"><label>Show me<select id="mode">${options.map(([value,label])=>`<option value="${value}" ${p.mode===value?'selected':''}>${esc(label)}</option>`).join('')}</select></label><span class="progress">${done} got it this session</span></div>${itemImage(item,true)}<p class="practice-prompt">${prompt}</p>${p.revealed?`<div class="practice-reveal"><h2>${esc(item.en||item.es)}</h2>${itemNames(item)}${credit(item)}</div><div class="practice-actions"><button class="btn secondary" id="again">Again</button><button class="btn" id="got">Got it</button></div>`:`<div class="practice-actions"><button class="btn" id="reveal">Reveal answer</button></div>`}</div>`}
function match(){const t=topic(),m=matchState(),item=t.items.find(x=>x.id===m.itemId)||t.items[0],langs=t.singular?t.languages:[['es','Spanish']];return `${back()}${nav()}<p class="eyebrow">${esc(t.title)} · Match</p><h1>Name it together.</h1><p class="lead">${t.singular?'Name the '+t.singular+' in each language.':'Translate the Swedish prompt into Spanish.'} Give the point to the speaker; judge answers and repeats together.</p><section class="panel stack"><div class="scores">${m.players.map((name,i)=>`<div class="score ${m.turn===i&&!m.ended?'turn':''}">${m.turn===i&&!m.ended?'<span class="badge">Naming turn</span>':''}<span>${esc(name)}</span><strong>${m.scores[i]}</strong></div>`).join('')}</div><div class="row">${m.players.map((name,i)=>`<label>Player ${i+1}<input data-player="${i}" value="${esc(name)}" maxlength="24"></label>`).join('')}</div>${m.ended?`<h2>Match ended</h2><p>${m.scores[0]===m.scores[1]?'Tie game':esc(m.players[m.scores[0]>m.scores[1]?0:1])+' wins'} · ${m.scores.join('–')}</p><div class="row"><button class="btn secondary" id="resume">Resume match</button><button class="btn" id="new">New match</button></div>`:`<div class="match-photo"><span class="photo-label">${t.singular?'Photo to name':'Swedish prompt'}</span>${itemImage(item,true)}${state.topicId==='spanish'?`<h2>${esc(item.sv)}</h2>`:''}</div><p class="small muted">${Object.keys(m.awards).length}/${langs.length} languages scored this round. Next turn and Pass advance to the next item.</p><div>${langs.map(([lang,label])=>`<div class="language"><span>${label}</span>${m.awards[lang]!==undefined?`<em>Point to ${esc(m.players[m.awards[lang]])}</em>`:m.players.map((name,i)=>`<button class="btn secondary" data-award="${lang}" data-speaker="${i}">+1 ${esc(name)}</button>`).join('')}</div>`).join('')}</div><div class="row"><button class="btn" id="next">Next turn</button><button class="btn secondary" id="pass">Pass</button><button class="btn secondary" id="undo" ${m.history.length?'':'disabled'}>Undo</button><button class="btn secondary" id="end">End match</button></div>`}<p class="status" role="status">${esc(m.message||'')}</p></section>`}
function render(){document.body.classList.toggle('practice-view',state.page==='practice');app.innerHTML=state.page==='home'?home():state.page==='topic'?overview():state.page==='learn'?learn():state.page==='practice'?practice():match();bind()}
function snapshot(){const m=matchState();m.history.push({scores:[...m.scores],turn:m.turn,itemId:m.itemId,awards:{...m.awards},ended:m.ended});if(m.history.length>100)m.history.shift()}
function nextItem(){const t=topic(),m=matchState(),index=t.items.findIndex(x=>x.id===m.itemId);m.itemId=t.items[((index<0?0:index)+1)%t.items.length].id}
function bind(){
  document.querySelectorAll('[data-topic]').forEach(x=>x.onclick=()=>{state.topicId=x.dataset.topic;state.page='topic';save();render()});
  document.querySelectorAll('[data-page]').forEach(x=>x.onclick=()=>{state.page=x.dataset.page;save();render()});
  if(state.page==='practice'){
    const p=practiceState(),t=topic();
    const mode=document.querySelector('#mode');if(mode)mode.onchange=e=>{p.mode=e.target.value;p.revealed=false;save();render()};
    const reveal=document.querySelector('#reveal');if(reveal)reveal.onclick=()=>{p.revealed=true;save();render()};
    for(const [id,val] of [['again','again'],['got','got']]){const x=document.querySelector('#'+id);if(x)x.onclick=()=>{const itemId=p.queue.shift();p.results[itemId]=val;p.queue=shuffle(p.queue);if(val==='again'){const position=p.queue.length?1+Math.floor(Math.random()*p.queue.length):0;p.queue.splice(position,0,itemId)}p.revealed=false;save();render()}}
    const restart=document.querySelector('#restart');if(restart)restart.onclick=()=>{p.queue=shuffle(t.items.map(x=>x.id));p.catalog=t.items.map(x=>x.id);p.revealed=false;save();render()};
  }
  if(state.page==='match'){
    const m=matchState();
    document.querySelectorAll('[data-player]').forEach(x=>x.onchange=()=>{m.players[+x.dataset.player]=x.value.trim()||`Player ${+x.dataset.player+1}`;save();render()});
    document.querySelectorAll('[data-award]').forEach(x=>x.onclick=()=>{if(m.awards[x.dataset.award]!==undefined)return;snapshot();const i=+x.dataset.speaker;m.awards[x.dataset.award]=i;m.scores[i]++;m.message=`Point to ${m.players[i]}`;save();render()});
    for(const [id,msg] of [['next','Next naming turn'],['pass','Turn passed']]){const x=document.querySelector('#'+id);if(x)x.onclick=()=>{snapshot();m.turn=1-m.turn;nextItem();m.awards={};m.message=msg;save();render()}}
    const undo=document.querySelector('#undo');if(undo)undo.onclick=()=>{const prior=m.history.pop();if(prior){Object.assign(m,prior);m.message='Last action undone';save();render()}};
    const end=document.querySelector('#end');if(end)end.onclick=()=>{snapshot();m.ended=true;m.message='';save();render()};
    const resume=document.querySelector('#resume');if(resume)resume.onclick=()=>{m.ended=false;save();render()};
    const n=document.querySelector('#new');if(n)n.onclick=()=>{state.matches[state.topicId]={...freshMatch(state.topicId),players:[...m.players]};save();render()};
  }
}
render();
